POST http://192.168.31.106:5433/users
Content-Type: application/json

{
  "name": "Test",
  "password": "Test"
}

###
PUT http://192.168.31.106:5433/users
Content-Type: application/json

{
  "user_id": 2,
  "first_name": "Peter",
  "last_name": "Parker",
  "email": "peter69parker@gmail.com",
  "password": "PP1pan2dziobak#",
  "date_of_birth": "12/12/1212",
  "sex": "Helicopter"
}

###
GET http://192.168.31.106:5433/users
Content-Type: application/json
