POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Peter",
  "last_name": "Parker",
  "email": "peter96parker@gmail.com",
  "password": "PP1pan2dziobak#",
  "date_of_birth": "12/12/1212",
  "sex": "Attack_Helicopter"
}

###
PUT http://localhost:3000/users
Content-Type: application/json

{
  "user_id": 2,
  "first_name": "Peter",
  "last_name": "Parker",
  "email": "peter96parker@gmail.com",
  "password": "PP1pan2dziobak#",
  "date_of_birth": "12/12/1212",
  "sex": "Helicopter"
}

###
GET http://localhost:3000/users
Content-Type: application/json
